version: '3'
services:
  app:
    env_file:
      - env
    build:
      context: .
      dockerfile: Dockerfile
    image: python:hr-app
    container_name: hr-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
  db:
    env_file:
      - env
    image: mariadb:10.5.8
    container_name: hr-app-db
